//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EInvoiceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Oid { get; set; }
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> ProductQty { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Product Product { get; set; }
    }
}
