//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EInvoiceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTable
    {
        public string InvoiceID { get; set; }
        public string ProductName { get; set; }
        public string UnitPrice { get; set; }
        public int ItemQuantity { get; set; }
        public string ItemTotalPrice { get; set; }
        public string InvoiceTotalPrice { get; set; }
        public string DateCreated { get; set; }
    }
}
